// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

type InstalledPak struct {
	Name         string
	DisplayName  string
	Type         string
	Version      string
	CanUninstall int64
}
